unique_ids:
  assets:
    standard-page.html: IDUXBMZHOW7XWJB4TU73ZJLXXCI6HUWR
    theme.css: WT45OV674XXC5QFJRTP4QYUSN2V744ZD
  forms:
    Form1: 3MZBD4ZVH46FUWYOWHKPKQOXHWYEH2FD
  modules: {}
  scripts: {}
  server_modules: {}
